language: python
python:
 - "3.7"
install:
 - pip install -r requirements.txt
script:
 - python -m unittest tests/tests_bla.py
deploy:
  provider: heroku
  api_key:
    secure: "3a186ccf-82eb-4f18-ab6b-2d358f6968e2"

